pipeline:
  name: customer_pipeline
  engine: duckdb
  
  defaults:
    patterns:
      rename: snake_case
      email: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
  types: 
      - type: str
        transform: ["trim", "upper"]
      - type: int
        try_cast: true
      - type: float
        format: "{:.2f}"
        try_cast: true
      - type: date
        format: "yyyy-MM-dd"

sources:
  - name: customer_input
    type: file
    format: csv
    path: "C:/Users/felipe.sampaio_visag/Documents/git/drune/examples/data/"
    options:
      header: 0
      delimiter: ","
      encoding: "utf-8"
    
    schema:
      columns:
        - name: customer_id
          rename: cd
          type: int
          constraints: 
            - rule: "not_null"
              on_fail: "fail"
            - rule: "unique"
              on_fail: "drop"
        - name: first_name
          type: str
          transform: "trim:upper"
        - name: last_name
          type: str
        - name: email
          type: str
          optional: true
          constraints:
            - rule: "pattern:'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'"
              on_fail: "drop"
        - name: document
          rename: doc
          type: str

target:
  name: dm_customer
  description: Processed customer data for analytics
  type: file
  format: csv
  path: "output/"
  mode: overwrite

  schema:
    primary_key: [customer_id]
    partition_by: []

    inherits:
      - from: customer_input
        exclude: [document]
    
    columns:
      - name: new_column
        type: str
        description: "Newly added column for additional information"  