pipeline:
  name: customer_pipeline

  defaults:
    patterns:
      rename: snake_case
      email: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
  types: 
      - type: str
        transform: trim|upper
      - type: int
        try_cast: true
      - type: float
        format: "{:.2f}"
        try_cast: true
      - type: date
        format: "yyyy-MM-dd"

sources:
  - name: customer_file
    type: file
    format: csv
    path: "C:/Users/felipe.sampaio_visag/Documents/repos/drune/examples/data/"
    options:
      header: 0
      delimiter: ","
      encoding: "utf-8"
    
    schema:
      columns:
        - name: customer_id
          rename: cd_customer
          description: Identifies the customer
          type: int
          constraints: 
            - rule: "not_null"
              on_fail: "warn"
            - rule: "unique"
              on_fail: "drop"
        - name: first_name
          rename: nm_first_name
          type: str
          transform: trim|upper
        - name: last_name
          rename: nm_last_name
          type: str
          transform: trim|upper
        - name: email
          rename: ds_email
          type: str
          transform: trim|lower
          optional: true
          constraints:
            - rule: pattern:'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'
              on_fail: set_null
        - name: document
          rename: nu_document
          type: str
        # - name: ds_login
        #   type: str
        #   transform: regex:email,^[^@]+

target:
  name: dm_customer
  description: Processed customer data for analytics
  type: file
  format: csv
  path: "output/"
  mode: overwrite

  schema:
    primary_key: [customer_id]
    partition_by: []

    inherits:
      - from: customer_file
        exclude: [document]
    
    columns:
      - name: new_column
        type: str
        description: "Newly added column for additional information"  